#!/bin/sh

apt-get install gdb
apt-get install cgdb
apt-get install clisp-module-gdbm
apt-get install gauche-gdbm
apt-get install gdb-avr
apt-get install gdb-bpf
apt-get install gdb-dbg
apt-get install gdb-mingw-w64
apt-get install gdb-mingw-w64-target
#apt-get install gdb-msp430
apt-get install gdb-multiarch
apt-get install gdbm-l10n
apt-get install gdbmtool
apt-get install gdbserver
apt-get install libdevel-gdb-perl
apt-get install libgdbm-compat-dev
apt-get install libgdbm-compat4
apt-get install libgdbm-dev
#apt-get install libgdbm-gst
#apt-get install libgdbm5
apt-get install libgdbm6
apt-get install libgdbussyncevo0
apt-get install libwgdb-dev
apt-get install libwgdb0
apt-get install lx-gdb
apt-get install nvidia-cuda-gdb
apt-get install pgdbf
#apt-get install pike7.8-gdbm
#apt-get install pike8.0-gdbm
apt-get install python-gdbm
apt-get install python-gdbm-dbg
apt-get install python3-gdbm
apt-get install python3-gdbm-dbg
apt-get install r-bioc-stringdb
#apt-get install rust-1.62-gdb
apt-get install rust-gdb
apt-get install slang-gdbm
apt-get install wireless-regdb
apt-get install xxgdb
